spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernate
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
#        current_session_context_class: thread

debug: false
logging:
  level:
    root: INFO
